version: '3.8'
services:
  server:
    build:
      context: ./
    image: qkd_ssh_image
    container_name: ssh_server
    network_mode: host
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    env_file:
      - server.env
  client:
    image: qkd_ssh_image
    container_name: ssh_client
    depends_on:
      - server
    network_mode: host
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    env_file:
      - client.env
